CREATE TABLE skateful_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_voted TIMESTAMP,
    admin BOOLEAN DEFAULT FALSE
);

ALTER TABLE skateful_skaters
    ADD COLUMN 
        added_by INTEGER REFERENCES skateful_users(id)
        ON DELETE SET NULL;