CREATE TABLE skateful_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES skateful_users(id),
    skater_id INTEGER REFERENCES skateful_skaters(id),
    comment TEXT NOT NULL,
    date_published TIMESTAMP DEFAULT now() NOT NULL,
    points INTEGER DEFAULT 0
)
